version: "3"
services:
  server:
    image: gitea/gitea:1.18.5
    container_name: cicd-stack-gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - cicd-stack
    volumes:
      - ./gitea-data:/data
    ports:
      - "3000:3000"
      - "222:22"

networks:
  cicd-stack:
    name: cicd-stack
    external: false
